import {
  SiBitcoin,
  SiEthereum,
  SiSolana,
  SiRipple,
  SiPolkadot,
  SiTether,
  SiCardano,
  SiLitecoin,
  SiChainlink,
  SiStellar,
  SiDogecoin,
  SiBinance,
  SiMonero,
  SiAlgorand,
  SiIota,
  SiDash,
  SiZcash,
  SiHelium,
  SiBitwig,
  SiFantom,
  SiNvidia,
  SiHedera,
  SiPolygon,
  SiIntel,
} from "react-icons/si";

const cryptoList = [
  {
    id: 1,
    name: "Bitcoin",
    price: "$57229",
    icon: SiBitcoin,
    category: "Altcoins",
  },
  {
    id: 2,
    name: "Ethereum",
    price: "$3023",
    icon: SiEthereum,
    category: "Altcoins",
  },
  {
    id: 3,
    name: "Solana",
    price: "$5923",
    icon: SiSolana,
    category: "Altcoins",
  },
  {
    id: 4,
    name: "Ripple",
    price: "$13.9",
    icon: SiRipple,
    category: "Altcoins",
  },
  {
    id: 5,
    name: "Polkadot",
    price: "$39.7",
    icon: SiPolkadot,
    category: "Altcoins",
  },
  {
    id: 6,
    name: "Tether",
    price: "$235",
    icon: SiTether,
    category: "Stablecoins",
  },
  {
    id: 7,
    name: "Cardano",
    price: "$1.22",
    icon: SiCardano,
    category: "Altcoins",
  },
  {
    id: 8,
    name: "Litecoin",
    price: "$158.4",
    icon: SiLitecoin,
    category: "Altcoins",
  },
  {
    id: 9,
    name: "Chainlink",
    price: "$25.13",
    icon: SiChainlink,
    category: "Altcoins",
  },
  {
    id: 10,
    name: "Stellar",
    price: "$0.39",
    icon: SiStellar,
    category: "Altcoins",
  },
  {
    id: 11,
    name: "Dogecoin",
    price: "$0.31",
    icon: SiDogecoin,
    category: "Memecoins",
  },
  {
    id: 12,
    name: "Binance Coin",
    price: "$389.7",
    icon: SiBinance,
    category: "Altcoins",
  },
  {
    id: 13,
    name: "Monero",
    price: "$245.6",
    icon: SiMonero,
    category: "Altcoins",
  },
  {
    id: 14,
    name: "Algorand",
    price: "$1.56",
    icon: SiAlgorand,
    category: "Altcoins",
  },
  { id: 15, name: "IOTA", price: "$1.29", icon: SiIota, category: "Altcoins" },
  { id: 16, name: "Dash", price: "$178.4", icon: SiDash, category: "Altcoins" },
  {
    id: 17,
    name: "Zcash",
    price: "$127.43",
    icon: SiZcash,
    category: "Altcoins",
  },
  {
    id: 18,
    name: "Helium",
    price: "$284.56",
    icon: SiHelium,
    category: "Altcoins",
  },
  {
    id: 19,
    name: "Bitwig",
    price: "$254.98",
    icon: SiBitwig,
    category: "Altcoins",
  },
  {
    id: 20,
    name: "Fantom",
    price: "$1.52",
    icon: SiFantom,
    category: "Altcoins",
  },
  {
    id: 21,
    name: "Nvidia",
    price: "$275.00",
    icon: SiNvidia,
    category: "Altcoins",
  },
  {
    id: 22,
    name: "Hedera",
    price: "$0.27",
    icon: SiHedera,
    category: "Altcoins",
  },
  {
    id: 23,
    name: "Intel",
    price: "$374.89",
    icon: SiIntel,
    category: "Altcoins",
  },
  {
    id: 24,
    name: "Polygon",
    price: "$1583.99",
    icon: SiPolygon,
    category: "Altcoins",
  },
];

export default cryptoList;
